/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WalletFileData {
  version: number
  address: string
  publicKey: string
  encryptedSk: string
  nonce: string
  tag: string
  accountIndex?: number
}
export interface WalletAccount {
  address: string
  publicKey: string
  secretKey: string
  accountIndex: number
  walletFile?: WalletFileData
}
export interface SignatureResult {
  algorithm: string
  signature: string
}
export interface WalletCreationResult {
  mnemonic: string
  walletFile: WalletFileData
}
export declare function sdkVersion(): string
export declare function rpcLineVersion(): string
export declare function generateMnemonic(): string
export declare function validateMnemonic(mnemonic: string): void
export declare function createWalletFile(password: string): WalletCreationResult
export declare function createHdWalletAccountFromMnemonic(mnemonic: string, password: string, accountIndex: number): WalletAccount
export declare function createHdWalletFileFromMnemonic(mnemonic: string, password: string): WalletAccount
export declare function recoverWalletFile(version: number, address: string, publicKey: string, encryptedSk: string, nonce: string, tag: string, accountIndex: number | undefined | null, mnemonic: string, password: string): WalletAccount
export declare function addressFromPublicKey(publicKeyHex: string): string
export declare function recoverHdWallet(mnemonic: string): WalletAccount
export declare function recoverHdWalletAccount(mnemonic: string, accountIndex: number): WalletAccount
export declare function signMessage(secretKeyHex: string, message: string): SignatureResult
export declare function verifyMessage(publicKeyHex: string, message: string, signatureHex: string): boolean
