/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CommitmentResult {
  commitment: string
  nonce: string
}
export interface ProofResult {
  proof: string
  publicInputs: string
  verificationKey: string
}
export declare function poseidonHash(inputs: Array<number>): string
export declare function computeCommitment(value: number, secretHex: string, nonceHex: string): CommitmentResult
export declare function computeNullifier(secretHex: string, nonceHex: string): string
export declare function generatePreimageProof(values: Array<number>): ProofResult
export declare function verifyPreimageProof(proofHex: string, vkJson: string, inputsJson: string): boolean
export declare function generateRangeProof(value: number, minVal: number, maxVal: number): ProofResult
export declare function verifyRangeProof(proofHex: string, vkJson: string, inputsJson: string): boolean
